function out1 = T02_func(a1,dh1,theta1,theta2)
%T02_FUNC
%    OUT1 = T02_FUNC(A1,DH1,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Aug-2019 12:24:02

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
out1 = reshape([t2.*t3,t3.*t4,t5,0.0,-t2.*t5,-t4.*t5,t3,0.0,t4,-t2,0.0,0.0,a1.*t2,a1.*t4,dh1,1.0],[4,4]);
