function out1 = T03_func(a1,a2,dh1,theta1,theta2,theta3)
%T03_FUNC
%    OUT1 = T03_FUNC(A1,A2,DH1,THETA1,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Aug-2019 12:24:03

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta3);
t5 = cos(theta3);
t6 = sin(theta2);
t7 = sin(theta1);
out1 = reshape([t2.*t3.*t5-t2.*t4.*t6,t3.*t5.*t7-t4.*t6.*t7,t3.*t4+t5.*t6,0.0,-t2.*t3.*t4-t2.*t5.*t6,-t3.*t4.*t7-t5.*t6.*t7,t3.*t5-t4.*t6,0.0,t7,-t2,0.0,0.0,a1.*t2+a2.*t2.*t3,a1.*t7+a2.*t3.*t7,dh1+a2.*t6,1.0],[4,4]);
