function out1 = T04_func(a1,a2,a3,dh1,theta1,theta2,theta3)
%T04_FUNC
%    OUT1 = T04_FUNC(A1,A2,A3,DH1,THETA1,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Aug-2019 12:24:03

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta3);
t5 = cos(theta3);
t6 = sin(theta2);
t7 = t2.*t3.*t5;
t8 = sin(theta1);
t9 = t3.*t5.*t8;
t10 = t3.*t4;
t11 = t5.*t6;
t12 = t10+t11;
out1 = reshape([t7-t2.*t4.*t6,t9-t4.*t6.*t8,t12,0.0,-t2.*t3.*t4-t2.*t5.*t6,-t3.*t4.*t8-t5.*t6.*t8,t3.*t5-t4.*t6,0.0,t8,-t2,0.0,0.0,a1.*t2+a3.*(t7-t2.*t4.*t6)+a2.*t2.*t3,a1.*t8+a3.*(t9-t4.*t6.*t8)+a2.*t3.*t8,dh1+a2.*t6+a3.*t12,1.0],[4,4]);
