function solx2 = theta3(a1,a3,dh1,theta1,theta2,x,y,z)
%THETA3
%    SOLX2 = THETA3(A1,A3,DH1,THETA1,THETA2,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Aug-2019 12:24:02

t2 = cos(theta2);
t3 = sin(theta2);
solx2 = -asin((-a1.*t3+dh1.*t2-t2.*z+t3.*x.*cos(theta1)+t3.*y.*sin(theta1))./a3);
