function solx = theta1(x,y)
%THETA1
%    SOLX = THETA1(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Aug-2019 12:23:43

t2 = 1.0./y;
t3 = x.^2;
t4 = y.^2;
t5 = t3+t4;
t6 = sqrt(t5);
solx = [atan(-t2.*(t6-x)).*-2.0;atan(t2.*(t6+x)).*-2.0];
